name: Hello World Docker Action
description: 'This container action says hello to the user!'
inputs:
  who-to-greet:
    required: True
    default: 'world'
    description: 'Who we are saying hello to'
outputs:
  time:
    description: 'The time this action was run'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
