name: GitHub Actions Demo

on:
  push:
    branches: [ main ]
    paths-ignore: [ .github/* ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '15 6 * * SUN'
  workflow_dispatch:
    inputs:
      Env:
        type: environment
        required: true

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo 'The event that triggered this workflow was ${{ github.event_name }}'
          echo 'The branch this workflow is running against is ${{ github.ref }}'
      - uses: actions/checkout@v4
      - run: tree
  Test:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: [ Build ]
    environment: Test
    steps:
      - run: echo 'Testing...'
  Load-Test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    environment: Load-Test
    needs: [ Build ]
    steps:
      - run: |
          echo 'Testing...'
          sleep 15
  Prod:
    runs-on: ubuntu-latest
    if: github.event.inputs.environment == 'Production'
    needs: [ Test, Load-Test ]
    environment:
      name: Production
      url: https://writeabout.net
    steps:
      - run: |
          echo 'Step 1 deploying...'
          sleep 10
          echo 'Step 2 deploying...'
          sleep 10
          echo 'Step 3 deploying...'
          sleep 10
          echo 'Step 4 deploying...'
          sleep 10
          echo 'Step 5 deploying...'
          sleep 10
