name: Container Action Test

on:
  push:
    paths: [ hello-world-docker-action/* ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./hello-world-docker-action
        with:
          who-to-greet: "Connor"
        id: hw-action
      - run: echo "The action was run at ${{ steps.hw-action.outputs.time }}"
